#
# MAKEFILE FOR HIG-17-005
#

.DEFAULT: all

#ANALYSIS NOTE
all: pdf

pdf:
	tdr --style=note b HIG-17-005

verb:
	tdr --style=note --verbose b HIG-17-005

pub:
	tdr --nodraft --style=note b HIG-17-005

clean:
	rm -v ../tmp/*

