#
# MAKEFILE FOR AN-16-378
#

.DEFAULT: all

#ANALYSIS NOTE
all: pdf

pdf:
	tdr --style=note b AN-16-378

verb:
	tdr --style=note --verbose b AN-16-378

pub:
	tdr --nodraft --style=note b AN-16-378

clean:
	rm -v ../tmp/*

